version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: TEST_USER
      POSTGRES_PASSWORD: TEST_PASSWORD
      POSTGRES_DB: TEST_DB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      target: runner
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://TEST_USER:TEST_PASSWORD@db:5432/TEST_DB?schema=public
      - PORT=3001
    depends_on:
      - db
volumes:
  postgres_data:
