version: '3.8'

services:
  postgres_test:
    image: postgres:12-alpine
    container_name: integration-tests-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'
