trigger: none

pr:
  branches:
    include:
      - test-1

pool:
  name: Azure Pipelines
  demands: java

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Instalar Node.js'

- script: npm install
  displayName: 'Instalar dependencias'

- script: npm run test:unit
  displayName: 'Ejecutar pruebas unitarias con cobertura'

- task: PublishTestResults@2
  displayName: 'Publicar resultados de pruebas'
  inputs:
    testResultsFiles: 'junit.xml'
    testRunTitle: 'Resultados de pruebas unitarias'

- task: PublishCodeCoverage@2
  displayName: 'Publicar reporte de cobertura'
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    pathToSources: '$(Build.SourcesDirectory)/src'
    failIfCoverageEmpty: true
    codecoverageTool: 'Cobertura'

- task: BuildQualityChecks@9
  displayName: 'Validar métricas de calidad'
  inputs:
    checkCoverage: true
    coverageType: 'line'
    coverageThreshold: '70'
    onlyFailBuildOnCoverageDecrease: false
    checkTests: true
    testResultsFailOption: 'fixed'
    minimumFailedTests: '0'
