trigger:
  branches:
    include:
      - feature/*
      - master

resources:
  repositories:
    - repository: templates
      type: git
      ref: feature/test
      name: RP-AZ-ARQ-FRAMEWORK/PIPELINES_TEMPLATES

stages:
  - stage: Run_Tests
    displayName: "Run Unit Tests"
    jobs:
      - template: workflow-templates\nodejs-run-tests.yaml@templates

