#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Verifica tipos de TypeScript
npm run tsc --noEmit

# Ejecuta todos los tests
npm run test:unit

# Ejecuta el linter en todo el proyecto
npm run lint
